<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFrameworks>net10.0-android</TargetFrameworks>
	  <!--<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net10.0-ios;net10.0-maccatalyst</TargetFrameworks>-->
	  <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>
	  <!--<WindowsPackageType>MSIX</WindowsPackageType>
	  <OutputType>exe</OutputType>
	  <Nullable>enable</Nullable>
	  <EnableMsixTooling>true</EnableMsixTooling>-->
	  <OutputType>Exe</OutputType>
	<UseWinUI>true</UseWinUI>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- MAUI properties -->
    <UseMaui>true</UseMaui>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.19041.0</TargetPlatformMinVersion>
	<RootNamespace>LocalChat</RootNamespace>
	<ApplicationTitle>Croccodillo</ApplicationTitle>
    <ApplicationId>com.bamburillio.lanchat</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>

    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<WindowsPackageType>None</WindowsPackageType>
		<EnableMsixTooling>true</EnableMsixTooling>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.70" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.70" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <MauiIcon Include="Resources\AppIcon\appicon.svg">
      <Color>#512BD4</Color>
      <ForegroundFile>Resources\AppIcon\appiconfg.svg</ForegroundFile>
    </MauiIcon>
    <!--<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />-->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <MauiImage Include="Resources\Images\*" />
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <GoogleServicesJson Include="Platforms\Android\google-services.json" Condition="Exists('Platforms\Android\google-services.json')" />
  </ItemGroup>

  <ItemGroup>
    <AndroidResource Include="Platforms\Android\Resources\**\*.xml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AppShell.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Remove="AppShell.xaml" />
    <MauiXaml Remove="Resources\Styles\Styles — копия.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Platforms\Android\Resources\Drawable\" />
  </ItemGroup>

  <ItemGroup>
    <MauiXaml Update="Platforms\Android\Resources\Styles\Styles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Platforms\Windows\App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Resources\Styles\Colors.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Resources\Styles\Styles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
  </ItemGroup>

  <ItemGroup>
    <None Update="Platforms\Android\Resources\Styles\Styles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Resources\Styles\Styles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
</Project>